version: '3.8'

services:
  postgres:
    image: postgres:14.4
    container_name: personal_finance_db
    restart: always
    environment:
      POSTGRES_USER: alepf
      POSTGRES_PASSWORD: alepf
      POSTGRES_DB: personal_finance_db
    ports:
      - "5432:5432"
    volumes:
      - C:/Users/alexb/me/personal_info/finance/structure/dev_env/volume/database:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U alepf -d personal_finance_db" ]
      interval: 3s
      timeout: 3s
      retries: 5